{
  "hash": "405bc327b722d9dfd9e749a87a91d0ca",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Learning Single Cell RNASeq with Seurat: Part 1\"\ndescription: \"Learning about the single cell RNASeq workflow using the Seurat package and Crohn's Disease data from the Broad Institute Single Cell Portal\"\nauthor: \"Sadie Wisotsky\"\ndate: \"2026-06-23\"\ncategories:\n  - RNASeq\n  - scRNASeq\n  - analysis\n  - R\n  - Seurat\nimage: \"umap_plots.png\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: show\n    code-tools: true\n---\n\n# Part 1: Basic workflow on Colon Stromal data\n\nI wanted to learn about single cell RNASeq and the Seurat package so I have chosen a data set that contains scRNASeq data from multiple tissue sites and compartments. This tissue has already been analyzed in this paper but I am hoping to use that as a check and as way to learn why they chose specific parameters and workflows. \n\nFor this first part, I will be following the basic workflow laid out in the Seurat tutorial for the Colon Stromal data. Further parts will expand out to the other 5 data sets and comparisons between them. \n\n## Step 1: Retrieve the data\n\nI downloaded the data from the Broad Institute Single Cell portal [here](https://singlecell.broadinstitute.org/single_cell/study/SCP1884/human-cd-atlas-study-between-colon-and-terminal-ileum#study-download). \n\nThere are 6 main data subsets for the expression data. Samples from the colon and the ileum and then broken down by compartment by stromal, epithelial, and immune cells. For this first post, I will be focusing on the colon stromal data.\n\nI wrote a function to create a custom Seurat object which will make it easier and more repeatable to read in the data for all 6 subsets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(Seurat)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'Seurat' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: SeuratObject\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'SeuratObject' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: sp\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'sp' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'SeuratObject'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, t\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\ncreate_seurat_obj <- function(path) {\n   matrix_path <- list.files(path, \".*raw.mtx\", full.names = TRUE)\n   barcodes_path <- list.files(path, \".*.barcodes.tsv\", full.names = TRUE)\n   features_path <-  list.files(path, \".*.features.tsv\", full.names = TRUE)\n  \n   sample_name <- matrix_path |> basename()  |> substr(1,6)\n\n   counts_matrix <- ReadMtx(\n     mtx = matrix_path,\n     cells = barcodes_path,\n     features = features_path,\n     cell.column = 1,     # Usually barcodes are in the first column\n     feature.column = 2   # Change to 1 if your gene file only has 1 column (IDs instead of Symbols)\n   )\n  # Create the Seurat object\n   obj <- CreateSeuratObject(counts = counts_matrix, project = sample_name)\n  \n  # Tag with custom metadata\n   obj$Tissue <- sample_name\n  \n   return(obj)\n}\n```\n:::\n\n\nI then create the Seurat object and look at what it is:\n\n::: {.cell}\n\n```{.r .cell-code}\nCO_STR <- create_seurat_obj(\"D:/R/scRNASeq_learning/data/SCP1884/expression/62a0c9f523a28233e1c9b06b/\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Feature names cannot have underscores ('_'), replacing with dashes\n('-')\n```\n\n\n:::\n\n```{.r .cell-code}\nCO_STR\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAn object of class Seurat \n28663 features across 39433 samples within 1 assay \nActive assay: RNA (28663 features, 0 variable features)\n 1 layer present: counts\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(CO_STR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFormal class 'Seurat' [package \"SeuratObject\"] with 13 slots\n  ..@ assays      :List of 1\n  .. ..$ RNA:Formal class 'Assay5' [package \"SeuratObject\"] with 8 slots\n  ..@ meta.data   :'data.frame':\t39433 obs. of  4 variables:\n  .. ..$ orig.ident  : Factor w/ 38 levels \"H106265\",\"H139073\",..: 13 13 13 13 13 13 13 13 13 13 ...\n  .. ..$ nCount_RNA  : num [1:39433] 19014 18425 18305 17791 17548 ...\n  .. ..$ nFeature_RNA: int [1:39433] 5135 5119 5024 4817 4690 4508 4721 4068 4129 4218 ...\n  .. ..$ Tissue      : chr [1:39433] \"CO_STR\" \"CO_STR\" \"CO_STR\" \"CO_STR\" ...\n  ..@ active.assay: chr \"RNA\"\n  ..@ active.ident: Factor w/ 38 levels \"H106265\",\"H139073\",..: 13 13 13 13 13 13 13 13 13 13 ...\n  .. ..- attr(*, \"names\")= chr [1:39433] \"N105446_L-GTGTGGCTCCGTCAAA\" \"N105446_L-CAATACGAGTCCCTAA\" \"N105446_L-CCCTGATAGTGTTCCA\" \"N105446_L-CATTGTTAGAGCCCAA\" ...\n  ..@ graphs      : list()\n  ..@ neighbors   : list()\n  ..@ reductions  : list()\n  ..@ images      : list()\n  ..@ project.name: chr \"CO_STR\"\n  ..@ misc        : list()\n  ..@ version     :Classes 'package_version', 'numeric_version'  hidden list of 1\n  .. ..$ : int [1:3] 5 4 0\n  ..@ commands    : list()\n  ..@ tools       : list()\n```\n\n\n:::\n:::\n\n\nCan see we have 39433 samples and 28663 features. Seurat as of v5.0 allows you to store different assays in layers. Here we can see that our only layer for now is counts and our assay is RNA. I probably won't dive deeper into this in this part but there is a [vignette here](https://satijalab.org/seurat/articles/seurat5_essential_commands) for those interested. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nLayers(CO_STR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"counts\"\n```\n\n\n:::\n:::\n\n\n## Step 2: QC\n\nthe first part of pre-processing the data is quality control. I will be following the guidelines outlined in the tutorial for now. Starting with calculating the percentage of mitochondrial (mt) contamination; a high value here is indictive of dying or low quality cells that we want to exclude from our analysis. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nCO_STR[[\"percent.mt\"]] <- PercentageFeatureSet(CO_STR, pattern = \"^MT-\")\n```\n:::\n\n\nI peak at the first 5.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show QC metrics for the first 5 cells\nhead(CO_STR@meta.data, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                           orig.ident nCount_RNA nFeature_RNA Tissue percent.mt\nN105446_L-GTGTGGCTCCGTCAAA    N105446      19014         5135 CO_STR   9.151152\nN105446_L-CAATACGAGTCCCTAA    N105446      18425         5119 CO_STR  16.575305\nN105446_L-CCCTGATAGTGTTCCA    N105446      18305         5024 CO_STR  14.220158\nN105446_L-CATTGTTAGAGCCCAA    N105446      17791         4817 CO_STR   7.104716\nN105446_L-TCCATGCGTTCGTTCC    N105446      17548         4690 CO_STR   8.086392\n```\n\n\n:::\n:::\n\n\nThen it is time to graph the metrics and visually check if our standard QC filters are appropriate:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize QC metrics as a violin plot\nVlnPlot(CO_STR, features = c(\"nCount_RNA\"), group.by=\"orig.ident\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Default search for \"data\" layer in \"RNA\" assay yielded no results;\nutilizing \"counts\" layer instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nhere's where I realize that I am doing this across multiple samples where the tutorial is across a single sample. For me, it is hard to see where the cutoff for number of features should be based on this so let's try to visualize it another way.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCO_STR@meta.data %>% \n    ggplot(aes(color=orig.ident, x=nCount_RNA, fill= orig.ident)) + \n    geom_density(alpha = 0.2) + \n    theme_classic() +\n    scale_x_log10() + \n    geom_vline(xintercept = 450,color=\"red\",linetype=\"dotted\")+ \n    geom_vline(xintercept = 3500,color=\"red\",linetype=\"dotted\")+ \n    geom_vline(xintercept = 15000,color=\"red\",linetype=\"dotted\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n## Step 3: Patient-Specific QC Filtering\n\nLooking at the density plots, it's clear that cells from different patients have different distributions of RNA count and feature count. Using a single global threshold might discard high-quality cells from some samples while keeping low-quality cells from others. \n\nTo address this, I will split the Colon Stromal object by patient (`orig.ident`), and apply customized thresholds for patients that show outlier characteristics (as identified in my exploratory work), while using a robust default threshold for the others.\n\nThe outliers and their thresholds:\n- **I124246**: High overall features/counts. Threshold: `min_feat = 500`, `max_feat = 6000`, `max_count = 25000`, `max_mt = 8`\n- **N104689**: High overall features/counts. Threshold: `min_feat = 500`, `max_feat = 5500`, `max_count = 20000`, `max_mt = 10`\n- **H106265**: Low overall features/counts. Threshold: `min_feat = 200`, `max_feat = 2000`, `max_count = 8000`, `max_mt = 5`\n- **Default (all other patients)**: `min_feat = 200`, `max_feat = 3000`, `max_count = 12000`, `max_mt = 5`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(purrr)\n\n# Split by patient identity\nstromal_list <- SplitObject(CO_STR, split.by = \"orig.ident\")\n\n# Define tailored patient-specific thresholds\npatient_thresholds <- list(\n  \"I124246\" = list(min_feat = 500, max_feat = 6000, max_count = 25000, max_mt = 8),\n  \"N104689\" = list(min_feat = 500, max_feat = 5500, max_count = 20000, max_mt = 10),\n  \"H106265\" = list(min_feat = 200, max_feat = 2000, max_count = 8000,  max_mt = 5),\n  # Additional tricky patients identified from summary statistics\n  \"I121881\" = list(min_feat = 200, max_feat = 6000, max_count = 28000, max_mt = 12),\n  \"I117351\" = list(min_feat = 200, max_feat = 6000, max_count = 31000, max_mt = 15),\n  \"N107306\" = list(min_feat = 200, max_feat = 6000, max_count = 30000, max_mt = 15),\n  \"N154787\" = list(min_feat = 200, max_feat = 6000, max_count = 20000, max_mt = 12),\n  \"N128208\" = list(min_feat = 200, max_feat = 6000, max_count = 28000, max_mt = 8),\n  \"N128624\" = list(min_feat = 200, max_feat = 6000, max_count = 25000, max_mt = 8),\n  \"N105446\" = list(min_feat = 500, max_feat = 6000, max_count = 25000, max_mt = 15)\n)\ndefault_thresh <- list(min_feat = 200, max_feat = 3000, max_count = 12000, max_mt = 5)\n\n# Filter each patient individually\nfiltered_stromal_list <- imap(stromal_list, function(obj, patient_id) {\n  # Fetch the custom threshold for this patient, OR use the default if not listed\n  thresh <- patient_thresholds[[patient_id]]\n  if (is.null(thresh)) {\n    thresh <- default_thresh\n  }\n  \n  # Calculate MT%\n  obj[[\"percent.mt\"]] <- PercentageFeatureSet(obj, pattern = \"^MT-\")\n  \n  # Identify cells passing thresholds\n  keep_cells <- colnames(obj)[\n    obj$nFeature_RNA > thresh$min_feat & \n    obj$nFeature_RNA < thresh$max_feat & \n    obj$nCount_RNA < thresh$max_count &\n    obj$percent.mt < thresh$max_mt\n  ]\n  \n  # If no cells pass, return NULL to avoid subsetting error\n  if (length(keep_cells) == 0) {\n    warning(paste(\"Patient\", patient_id, \"has no cells passing thresholds and will be excluded.\"))\n    return(NULL)\n  }\n  \n  # Apply tailored filtering\n  obj <- subset(obj, cells = keep_cells)\n  return(obj)\n})\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in .f(.x[[i]], .y[[i]], ...): Patient N117351 has no cells passing\nthresholds and will be excluded.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in .f(.x[[i]], .y[[i]], ...): Patient N178961 has no cells passing\nthresholds and will be excluded.\n```\n\n\n:::\n\n```{.r .cell-code}\n# Remove NULL elements\nfiltered_stromal_list <- compact(filtered_stromal_list)\n\n# Merge back into a single clean Seurat object\nCO_STR_clean <- merge(\n  x = filtered_stromal_list[[1]], \n  y = filtered_stromal_list[-1],\n  project = \"CO_STR_Clean\"\n)\n\n# Print comparison of cell counts\ncat(\"Original cells:\", ncol(CO_STR), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOriginal cells: 39433 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Filtered cells:\", ncol(CO_STR_clean), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFiltered cells: 24808 \n```\n\n\n:::\n:::\n\n\n## Step 4: Normalization & Variable Feature Selection\n\nNext, I normalize the counts to control for sequencing depth and find the 2,000 most highly variable genes across cells, which will be used for linear dimensionality reduction (PCA).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Standard log-normalization\nCO_STR_clean <- NormalizeData(CO_STR_clean, normalization.method = \"LogNormalize\", scale.factor = 10000)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.4\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.5\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.6\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.7\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.8\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.9\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.10\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.11\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.12\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.13\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.14\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.15\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.16\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.17\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.18\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.19\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.20\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.21\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.22\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.23\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.24\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.25\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.26\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.27\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.28\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.29\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.30\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.31\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.32\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.33\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.34\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.35\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNormalizing layer: counts.36\n```\n\n\n:::\n\n```{.r .cell-code}\n# Find variable features\nCO_STR_clean <- FindVariableFeatures(CO_STR_clean, selection.method = \"vst\", nfeatures = 2000)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -1.552\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.4976\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 1.2021e-14\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.090619\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.1222\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.30103\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 5.6189e-15\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: at -1.1315\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: radius 0.00030922\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: all data on boundary of neighborhood. make span bigger\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -1.1315\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.017585\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.031008\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: zero-width neighborhood. make span bigger\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.4\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.5\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.6\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.7\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.8\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.9\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -1.5746\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.31938\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 2.0431e-29\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.031008\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.10\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.11\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.12\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.6766\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.4948\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 1.093e-14\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.090619\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.13\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.8718\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.49649\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 3.8716e-15\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.090619\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.14\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.2447\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.49914\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 1.6385e-14\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.22764\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.15\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.16\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.3756\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.49861\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 6.3513e-15\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.090619\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.17\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.18\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.4573\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.4967\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 1.4656e-14\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.090619\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.19\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.4622\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.32072\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 8.4065e-29\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.090619\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.20\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.21\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.22\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.1945\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.30103\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 4.6589e-15\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.23\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.24\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.3646\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.30103\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 3.6584e-15\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.25\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.4842\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.49738\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 1.8514e-14\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.090619\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.26\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.27\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.28\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.29\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -1.5493\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.31886\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 4.6777e-28\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.090619\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.30\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.8811\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.30103\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 1.3072e-14\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.31\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.32\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.33\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.3855\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.49904\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 1.2264e-14\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.090619\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.34\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.35\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: pseudoinverse used at -2.3756\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: neighborhood radius 0.32059\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: reciprocal condition number 7.8717e-28\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,\n: There are other near singularities as well. 0.090619\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFinding variable features for layer counts.36\n```\n\n\n:::\n\n```{.r .cell-code}\n# Identify top 10 variable features and plot\ntop10 <- head(VariableFeatures(CO_STR_clean), 10)\nplot1 <- VariableFeaturePlot(CO_STR_clean)\nplot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWhen using repel, set xnudge and ynudge to 0 for optimal results\n```\n\n\n:::\n\n```{.r .cell-code}\nplot2\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in scale_x_log10(): log-10 transformation introduced infinite values.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n## Step 5: Scaling & PCA\n\nI scale the data so that each gene has a mean expression of 0 and a variance of 1 across all cells. This ensures that highly expressed genes do not dominate the PCA. Then, I run PCA on the variable features.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCO_STR_clean <- ScaleData(CO_STR_clean)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nCentering and scaling data matrix\n```\n\n\n:::\n\n```{.r .cell-code}\nCO_STR_clean <- RunPCA(CO_STR_clean, npcs = 30, verbose = FALSE)\n\n# Visualize PCA load and elbow plot\nElbowPlot(CO_STR_clean, ndims = 30)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## Step 6: Batch Integration using Harmony\n\nSince our cells come from 38 different patient samples, we are very likely to observe patient-specific clusters due to technical variations or individual genetic baselines (batch effects). To align equivalent cell populations across patients, I will integrate the datasets using the **Harmony** integration method.\n\nIn Seurat v5, this is streamlined using the `IntegrateLayers` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(harmony)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'harmony' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: Rcpp\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'Rcpp' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n• This is Harmony2 version 2.0.5\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n• Read the guide: run vignette(\"quickstart\", package=\"harmony\")\n• Get help: Visit the website at <https://korsunskylab.github.io/harmony2/> and\nreport issues on <https://github.com/immunogenomics/harmony/issues>\n```\n\n\n:::\n\n```{.r .cell-code}\n# Run Harmony Integration\nCO_STR_clean <- IntegrateLayers(\n  object = CO_STR_clean, \n  method = HarmonyIntegration,\n  orig.reduction = \"pca\", \n  new.reduction = \"harmony\",\n  verbose = FALSE\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe `features` argument is ignored by `HarmonyIntegration`.\nThis message is displayed once per session.\n```\n\n\n:::\n:::\n\n\n## Step 7: Clustering & UMAP Visualization\n\nWith the integrated representation (`harmony` reduction) ready, I will build the Shared Nearest Neighbor (SNN) graph, find clusters, and run UMAP for visualization. I'll use 20 dimensions of the integrated space.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Build SNN Graph and Find Clusters on integrated space\nCO_STR_clean <- FindNeighbors(CO_STR_clean, reduction = \"harmony\", dims = 1:20)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nComputing nearest neighbor graph\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'future' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nComputing SNN\n```\n\n\n:::\n\n```{.r .cell-code}\nCO_STR_clean <- FindClusters(CO_STR_clean, resolution = 0.5, verbose = FALSE)\n\n# Run UMAP\nCO_STR_clean <- RunUMAP(CO_STR_clean, reduction = \"harmony\", dims = 1:20)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The default method for RunUMAP has changed from calling Python UMAP via reticulate to the R-native UWOT using the cosine metric\nTo use Python UMAP via reticulate, set umap.method to 'umap-learn' and metric to 'correlation'\nThis message will be shown once per session\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n12:42:41 UMAP embedding parameters a = 0.9922 b = 1.112\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n12:42:41 Read 24808 rows and found 20 numeric columns\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n12:42:41 Using Annoy for neighbor search, n_neighbors = 30\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n12:42:41 Building Annoy index with metric = cosine, n_trees = 50\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n0%   10   20   30   40   50   60   70   80   90   100%\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n[----|----|----|----|----|----|----|----|----|----|\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n**************************************************|\n12:42:42 Writing NN index file to temp file C:\\Users\\rgnes\\AppData\\Local\\Temp\\RtmpqCOhpx\\file8507944204\n12:42:42 Searching Annoy index using 1 thread, search_k = 3000\n12:42:46 Annoy recall = 100%\n12:42:46 Commencing smooth kNN distance calibration using 1 thread with target n_neighbors = 30\n12:42:47 Initializing from normalized Laplacian + noise (using RSpectra)\n12:42:48 Commencing optimization for 200 epochs, with 1094230 positive edges\n12:42:48 Using rng type: pcg\n12:43:08 Optimization finished\n```\n\n\n:::\n:::\n\n\nLet's visualize the results! I will plot the cells colored by cluster and patient identity side-by-side using the `patchwork` library. This allows us to verify if Harmony successfully mixed the patient samples while preserving biological differences.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'patchwork' was built under R version 4.5.3\n```\n\n\n:::\n\n```{.r .cell-code}\np1 <- DimPlot(CO_STR_clean, reduction = \"umap\", group.by = \"seurat_clusters\", label = TRUE) + \n  ggtitle(\"Integrated UMAP: Clusters\") + \n  theme_minimal()\n\np2 <- DimPlot(CO_STR_clean, reduction = \"umap\", group.by = \"orig.ident\", label = FALSE) + \n  ggtitle(\"Integrated UMAP: Patients\") + \n  theme_minimal() +\n  theme(legend.position = \"none\") # Hide large patient legend\n\n# Render the combined plot\np1 + p2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Save the plot for the blog post preview thumbnail\nggsave(\"umap_plots.png\", plot = p1 + p2, width = 10, height = 5)\n```\n:::\n\n\nWe can see that cells from different patients are well-mixed within the same clusters, indicating that the Harmony integration successfully corrected for batch effects! In the next parts, we will extend this pipeline to the other tissue compartments (epithelial and immune) and dive deeper into biological characterization and marker identification.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}